### ISSUE TITLE
Outlook 2007 | 2010 bad display

### ISSUE THREAD

**Issue by etiks3** [leemunroe/htmlemail#9] opened 2017-09-18 07:56 UTC
Hi there,

I'm using your templates, but it's not working properly in Outlook 2007 and outlook 2010.
Is there a trick to workaround it?
Thanks for your prompt reply.

Sylvain

**Comment by leemunroe** [comment] 2017-09-20 05:16
@etiks3 Hey Sylvain, sorry to hear that. Can you email me hello@htmlemail.io with the following and I'll try to figure out what the issue is:

1. More details about what is not behaving as expected
2. The code you're sending (you can use http://codeshare.io to privately share your code)
3. A screenshot of what you're seeing in Outlook 2007 and 2010

Thanks

**Comment by leemunroe** [comment] 2017-10-17 05:44
Closing as resolved over email. Thanks @etiks3

**Closed by leemunroe** 2017-10-17 05:44 UTC
